Repository dnd-side-project/dnd-10th-6-frontend, pull requests merged in 2024-02, with the labels that each got.

#11 Chore: 스토리북 배포 자동화 적용
  .eslintrc.json
  .github/workflows/storybook.yaml
  .gitignore
  .pnp.cjs
  .storybook/main.ts
  .tool-versions
  components/button/index.tsx
  components/carousel/index.tsx
  components/inputbox/index.tsx
  components/login-button.tsx
  env.d.ts
  error.ts
  lib/client/auth.ts
  lib/client/namui-api.ts
  lib/client/utils.ts
  lib/server/auth.ts
  lib/server/utils.ts
  lib/server/with-handler.ts
  package.json
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  pages/api/auth/[provider].ts
  pages/index.tsx
  pages/signin.tsx
  static.d.ts
  tsconfig.json
  yarn.lock
Labels: 🧹 CHORE

#9 feat: 타이포그래피 등록하기
  components/button/button.stories.tsx
  components/button/index.tsx
  components/typography/index.tsx
  components/typography/typography.stories.tsx
  pages/_app.tsx
Labels: 🛠️ FEATURE

#15 컬러칩 세팅, tailwind config 등록
  components/colors/colors.stories.mdx
  pages/_app.tsx
  pages/index.tsx
  styles/theme/colors.ts
  tailwind.config.ts
  tsconfig.json
Labels: 🛠️ FEATURE, 🧹 CHORE

#16 Modal 구현
  .pnp.cjs
  components.json
  components/modal/index.tsx
  components/modal/modal.stories.tsx
  components/ui/dialog.tsx
  lib/utils.ts
  package.json
  pages/index.tsx
  styles/global.css
  tailwind.config.ts
  yarn.lock
Labels: 🛠️ FEATURE

#17 Feat: 인증모듈 제작
  .pnp.cjs
  constants.ts
  env.d.ts
  error.ts
  layout/base-layout.tsx
  lib/auth.ts
  lib/client/auth.ts
  lib/client/namui-api.ts
  lib/namui-api.ts
  lib/server/auth.ts
  lib/server/utils.ts
  lib/server/with-handler.ts
  package.json
  pages/_app.tsx
  pages/api/auth/[provider].ts
  pages/api/auth/signout.ts
  pages/index.tsx
  pages/signin.tsx
  provider/session-provider.tsx
  yarn.lock
Labels: 🛠️ FEATURE

#23 feat: 병합 충돌 & 타이포 mdx 로 수정
  .pnp.cjs
  components/onboard/index.tsx
  components/radioButton/index.tsx
  components/typography/index.tsx
  components/typography/typography.stories.mdx
  components/typography/typography.stories.tsx
  components/ui/radio-group.tsx
  package.json
  tailwind.config.ts
  tsconfig.json
  yarn.lock
Labels: 🛠️ FEATURE

#25 라디오버튼, 콤보박스 UI 토큰 구현
  .pnp.cjs
  components/combobox/index.tsx
  components/radioButton/index.tsx
  components/typography/typography.stories.mdx
  components/ui/radio-group.tsx
  package.json
  pages/test.tsx
  styles/theme/colors.ts
  tailwind.config.ts
  yarn.lock
Labels: 🛠️ FEATURE

#28 인증관련 테스트 오류사항 변경
  lib/namui-api.ts
  pages/_app.tsx
  pages/api/auth/[provider].ts
  provider/session-provider.tsx
Labels: 🐛 BUG

#29 콘솔 아스키 아트 추가
  pages/_document.tsx
Labels: 🧹 CHORE

#31 통계화면 2차 구현
  components/button/index.tsx
  components/dashboard/best-worth/index.tsx
  components/dashboard/character/index.tsx
  components/dashboard/money/index.tsx
  components/filter-button/index.tsx
  components/header/index.tsx
  hooks/use-in-view-ref.ts
  pages/dashboard/index.tsx
  pages/index.tsx
  pages/onboard/index.tsx
  provider/session-provider.tsx
  styles/theme/colors.ts
  tailwind.config.ts
Labels: 🛠️ FEATURE

#32 통계화면 완성
  .pnp.cjs
  components/combobox/index.tsx
  components/dashboard/best-worth/index.tsx
  components/dashboard/happy/index.tsx
  components/dashboard/money/index.tsx
  components/dashboard/sad/index.tsx
  components/form-contents/InputKnowing.tsx
  components/form-contents/InputName.tsx
  components/funnel/createFunnel.ts
  components/funnel/index.tsx
  components/header/index.tsx
  components/inputLabel/index.tsx
  components/landing/WriterLanding.tsx
  components/onboard/index.tsx
  components/template/InfoInsertTemplate.tsx
  contexts/useFunnelContext.ts
  hooks/useFunnel.ts
  layout/base-layout.tsx
  package.json
  pages/dashboard/index.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/onboard/index.tsx
  pages/surveys/index.tsx
  tailwind.config.ts
  yarn.lock
Labels: 🛠️ FEATURE

#34 알림, 설정 화면 구현하기
  components/compositions/dashboard/best-worth/index.tsx
  components/compositions/dashboard/character/index.tsx
  components/compositions/dashboard/happy/index.tsx
  components/compositions/dashboard/money/index.tsx
  components/compositions/dashboard/sad/index.tsx
  components/compositions/dashboard/tree-info.tsx
  components/compositions/header/alert/alert-card.tsx
  components/compositions/header/alert/index.tsx
  components/compositions/header/edit-setting/index.tsx
  components/compositions/header/setting/index.tsx
  components/compositions/header/write-list/index.tsx
  components/compositions/header/write-list/wirte-list-card.tsx
  components/header/index.tsx
  components/knowing-filter-group/index.tsx
  components/modal/index.tsx
  components/ui/dialog/index.tsx
  components/ui/drawer/index.tsx
  layout/base-layout.tsx
  pages/dashboard/index.tsx
  pages/test.tsx
  styles/theme/colors.ts
  tailwind.config.ts
Labels: 🛠️ FEATURE

#42 사용자 로그인/회원가입 플로우 구현
  components/compositions/question/Third.tsx
  components/header/index.tsx
  components/inputLabel/index.tsx
  layout/HOC/with-auth.tsx
  lib/namui-api.ts
  lib/server/with-handler.ts
  pages/api/auth/[provider].ts
  pages/api/auth/signup.ts
  pages/dashboard/index.tsx
  pages/index.tsx
  pages/signup/index.tsx
  provider/session-provider.tsx
Labels: 🛠️ FEATURE

#45 만료 토큰 검증 및 재발급 로직 추가
  components/button/index.tsx
  components/carousel/index.tsx
  components/compositions/dashboard/character/index.tsx
  components/compositions/dashboard/tree-info.tsx
  components/compositions/header/setting/index.tsx
  components/header/index.tsx
  components/icons/welcome-trees.tsx
  components/landing/WriterLanding.tsx
  components/modal/index.tsx
  components/onboard/index.tsx
  constants.ts
  hooks/use-scroll-direction.ts
  layout/HOC/with-auth.tsx
  layout/base-layout.tsx
  layout/form-layout.tsx
  lib/namui-api.ts
  lib/server/with-handler.ts
  middleware.ts
  page.d.ts
  pages/_app.tsx
  pages/api/auth/[provider].ts
  pages/api/auth/refresh.ts
  pages/api/auth/signout.ts
  pages/api/auth/signup.ts
  pages/dashboard/index.tsx
  pages/index.tsx
  pages/onboard/index.tsx
  provider/session-provider.tsx
  tailwind.config.ts
Labels: 🛠️ FEATURE

#46 웰컴페이지 구현하기
  lib/client/utils.ts
  pages/dashboard/index.tsx
  pages/signup/index.tsx
  pages/welcome/index.tsx
Labels: 🛠️ FEATURE

#48 내 정원 및 답변 상세보기 UI 구현
  components/compositions/answers/answer-detail/index.tsx
  components/compositions/tree-card/index.tsx
  middleware.ts
  model/tree.entity.tsx
  pages/answers/index.tsx
  pages/garden/index.tsx
  styles/global.css
  styles/theme/colors.ts
  tailwind.config.ts
Labels: 🛠️ FEATURE

#49 feat: 설문생성 시 닉네임 글자수 제한
  components/survey/survey-form.tsx
  hooks/useQuestionsForm.ts
  pages/surveys/questions/index.tsx
Labels: 🛠️ FEATURE

#50 fix: 파이차트 애니메이션 옵저버 복구
  components/compositions/dashboard/best-worth/index.tsx
Labels: 🐛 BUG, 🛠️ FEATURE

#51 feat: 설문 완료 이후 플로우 추가
  components/share-modal/index.tsx
  pages/submit/index.tsx
  pages/surveys/questions/index.tsx
Labels: 🛠️ FEATURE

#60 [NW-21] 로그인 이후 화면 처리용 csrf 추가
  pages/api/auth/[provider].ts
  pages/csrf/index.tsx
  pages/signup/index.tsx
  pages/surveys/index.tsx
  provider/session-provider.tsx
Labels: 🛠️ FEATURE

#62 [QA] 디자인 및 정책 일부 수정 사항 반영
  components/dashboard-container/detail-drawer.tsx
  components/dashboard-container/index.tsx
  components/survey/survey-form.tsx
  pages/answers/index.tsx
  pages/surveys/index.tsx
Labels: 🛠️ FEATURE

#63 [QA] 설문 제출시 대기시간 제거
  pages/surveys/questions/index.tsx
Labels: 🐛 BUG

#70 [QA] 라디오 버튼의 focus 및 제출 disabled 오류
  components/survey/survey-form.tsx
Labels: 🐛 BUG

#68 [Feat] 내 정원에 공유버튼 추가
  pages/garden/index.tsx
Labels: 🛠️ FEATURE

#74 내가 받은 설문 자세히 보기 추가
  components/compositions/dashboard/best-worth/index.tsx
  components/compositions/dashboard/happy/index.tsx
  components/compositions/dashboard/money/index.tsx
  components/compositions/dashboard/sad/index.tsx
  components/compositions/dashboard/tree-info.tsx
  components/dashboard-container/detail-drawer.tsx
  hooks/use-detail-drawer.ts
  hooks/use-drawer.ts
  model/dashboard.entity.ts
  model/tree.entity.tsx
  pages/dashboard/index.tsx
  pages/garden/index.tsx
Labels: 🛠️ FEATURE

#75 feat: 내가받은 설문상세 스켈레톤 추가
  components/badge/period/index.tsx
  components/badge/relation/index.tsx
  pages/answers/index.tsx
  queries/surveys.ts
Labels: 🛠️ FEATURE

#78 [NW-13, NW-33] 트리 카드 및 라우팅 QA 사항 추가
  components/compositions/tree-card/index.tsx
  components/header/index.tsx
  pages/dashboard/index.tsx
  pages/garden/index.tsx
  styles/global.css
Labels: 🛠️ FEATURE
